#!/bin/bash

rm -rf build

cmake -B build -DPHOTON_BUILD_TESTING=ON -DPHOTON_ENABLE_FSTACK_DPDK=ON

# cmake -B build -DPHOTON_BUILD_TESTING=ON -DPHOTON_ENABLE_SPDK=ON

# cmake -B build -DPHOTON_BUILD_TESTING=ON -DPHOTON_ENABLE_FSTACK_DPDK=ON -DPHOTON_ENABLE_SPDK=ON

make -C build -j 16