#include "photon/extend/mime-types.h"

const char* MimeTypes::getType(const char * extension)  {
  const char *dot = strrchr(extension, '.');
  if (dot) {
    if ( dot != extension) {
      extension = dot;
    }

    extension++;
  }

  int min = 0;
  int max = (sizeof(types) / sizeof(*types) - 1);

  while (min <= max) {
    int i = (int)(((max + min) / 2) + 0.5);
    int order = strcmpi(extension, types[i].fileExtension);

    if (order == 0) {
      return types[i].mimeType;
    } else if (order > 0) {
      min = i + 1;
    } else {
      max = i - 1;
    }
  }

  return NULL;
}

const char* MimeTypes::getExtension(const char * type, int skip)  {
  int length = (sizeof(types) / sizeof(*types));

  for (int i = 0; i < length; i++) {
    if (strcmpi(type, types[i].mimeType) == 0) {
      if (skip-- <= 0) {
        return types[i].fileExtension;
      }
    }
  }

  return NULL;
}

// https://www.geeksforgeeks.org/write-your-own-strcmp-which-ignores-cases/
int MimeTypes::strcmpi(const char *s1, const char *s2) {
  int i;

  for (i = 0; s1[i] && s2[i]; ++i) {
    if (s1[i] == s2[i] || (s1[i] ^ 32) == s2[i]) {
      continue;
    } else {
      break;
    }
  }

  if (s1[i] == s2[i]) {
    return 0;
  }

  if ((s1[i] | 32) < (s2[i] | 32)) {
    return -1;
  }

  return 1;
}

// Source: https://raw.githubusercontent.com/broofa/node-mime/master/types/standard.json
MimeTypes::entry MimeTypes::types[347] =  {
        {"*3gpp","audio/3gpp",false},
        {"*jpm","video/jpm",false},
        {"*mp3","audio/mp3",false},
        {"*rtf","text/rtf",true},
        {"*wav","audio/wave",false},
        {"*xml","text/xml",true},
        {"3g2","video/3gpp2",false},
        {"3gp","video/3gpp",false},
        {"3gpp","video/3gpp",false},
        {"ac","application/pkix-attr-cert",false},
        {"adp","audio/adpcm",false},
        {"ai","application/postscript",false},
        {"apng","image/apng",false},
        {"appcache","text/cache-manifest",true},
        {"asc","application/pgp-signature",false},
        {"atom","application/atom+xml",true},
        {"atomcat","application/atomcat+xml",true},
        {"atomsvc","application/atomsvc+xml",true},
        {"au","audio/basic",false},
        {"aw","application/applixware",false},
        {"bdoc","application/bdoc",false},
        {"bin","application/octet-stream",false},
        {"bmp","image/bmp",false},
        {"bpk","application/octet-stream",false},
        {"buffer","application/octet-stream",false},
        {"ccxml","application/ccxml+xml",true},
        {"cdmia","application/cdmi-capability",false},
        {"cdmic","application/cdmi-container",false},
        {"cdmid","application/cdmi-domain",false},
        {"cdmio","application/cdmi-object",false},
        {"cdmiq","application/cdmi-queue",false},
        {"cer","application/pkix-cert",false},
        {"cgm","image/cgm",false},
        {"class","application/java-vm",false},
        {"coffee","text/coffeescript",true},
        {"conf","text/plain",true},
        {"cpt","application/mac-compactpro",false},
        {"crl","application/pkix-crl",false},
        {"css","text/css",true},
        {"csv","text/csv",true},
        {"cu","application/cu-seeme",false},
        {"davmount","application/davmount+xml",true},
        {"dbk","application/docbook+xml",true},
        {"deb","application/octet-stream",false},
        {"def","text/plain",true},
        {"deploy","application/octet-stream",false},
        {"disposition-notification","message/disposition-notification",false},
        {"dist","application/octet-stream",false},
        {"distz","application/octet-stream",false},
        {"dll","application/octet-stream",false},
        {"dmg","application/octet-stream",false},
        {"dms","application/octet-stream",false},
        {"doc","application/msword",false},
        {"dot","application/msword",false},
        {"drle","image/dicom-rle",false},
        {"dssc","application/dssc+der",false},
        {"dtd","application/xml-dtd",true},
        {"dump","application/octet-stream",false},
        {"ear","application/java-archive",false},
        {"ecma","application/ecmascript",false},
        {"elc","application/octet-stream",false},
        {"emf","image/emf",false},
        {"eml","message/rfc822",false},
        {"emma","application/emma+xml",true},
        {"eps","application/postscript",false},
        {"epub","application/epub+zip",false},
        {"es","application/ecmascript",false},
        {"exe","application/octet-stream",false},
        {"exi","application/exi",false},
        {"exr","image/aces",false},
        {"ez","application/andrew-inset",false},
        {"fits","image/fits",false},
        {"g3","image/g3fax",false},
        {"gbr","application/rpki-ghostbusters",false},
        {"geojson","application/geo+json",true},
        {"gif","image/gif",false},
        {"glb","model/gltf-binary",false},
        {"gltf","model/gltf+json",true},
        {"gml","application/gml+xml",true},
        {"gpx","application/gpx+xml",true},
        {"gram","application/srgs",false},
        {"grxml","application/srgs+xml",true},
        {"gxf","application/gxf",false},
        {"gz","application/gzip",false},
        {"h261","video/h261",false},
        {"h263","video/h263",false},
        {"h264","video/h264",false},
        {"heic","image/heic",false},
        {"heics","image/heic-sequence",false},
        {"heif","image/heif",false},
        {"heifs","image/heif-sequence",false},
        {"hjson","application/hjson",true},
        {"hlp","application/winhlp",false},
        {"hqx","application/mac-binhex40",false},
        {"htm","text/html",true},
        {"html","text/html",true},
        {"ics","text/calendar",true},
        {"ief","image/ief",false},
        {"ifb","text/calendar",true},
        {"iges","model/iges",false},
        {"igs","model/iges",false},
        {"img","application/octet-stream",false},
        {"in","text/plain",true},
        {"ini","text/plain",true},
        {"ink","application/inkml+xml",true},
        {"inkml","application/inkml+xml",true},
        {"ipfix","application/ipfix",false},
        {"iso","application/octet-stream",false},
        {"jade","text/jade",true},
        {"jar","application/java-archive",false},
        {"jls","image/jls",false},
        {"jp2","image/jp2",false},
        {"jpe","image/jpeg",false},
        {"jpeg","image/jpeg",false},
        {"jpf","image/jpx",false},
        {"jpg","image/jpeg",false},
        {"jpg2","image/jp2",false},
        {"jpgm","video/jpm",false},
        {"jpgv","video/jpeg",false},
        {"jpm","image/jpm",false},
        {"jpx","image/jpx",false},
        {"js","application/javascript",false},
        {"json","application/json",true},
        {"json5","application/json5",true},
        {"jsonld","application/ld+json",true},
        {"jsonml","application/jsonml+json",true},
        {"jsx","text/jsx",true},
        {"kar","audio/midi",false},
        {"ktx","image/ktx",false},
        {"less","text/less",true},
        {"list","text/plain",true},
        {"litcoffee","text/coffeescript",true},
        {"log","text/plain",true},
        {"lostxml","application/lost+xml",true},
        {"lrf","application/octet-stream",false},
        {"m1v","video/mpeg",false},
        {"m21","application/mp21",false},
        {"m2a","audio/mpeg",false},
        {"m2v","video/mpeg",false},
        {"m3a","audio/mpeg",false},
        {"m4a","audio/mp4",false},
        {"m4p","application/mp4",false},
        {"ma","application/mathematica",false},
        {"mads","application/mads+xml",true},
        {"man","text/troff",true},
        {"manifest","text/cache-manifest",true},
        {"map","application/json",true},
        {"mar","application/octet-stream",false},
        {"markdown","text/markdown",true},
        {"mathml","application/mathml+xml",true},
        {"mb","application/mathematica",false},
        {"mbox","application/mbox",false},
        {"md","text/markdown",true},
        {"me","text/troff",true},
        {"mesh","model/mesh",false},
        {"meta4","application/metalink4+xml",true},
        {"metalink","application/metalink+xml",true},
        {"mets","application/mets+xml",true},
        {"mft","application/rpki-manifest",false},
        {"mid","audio/midi",false},
        {"midi","audio/midi",false},
        {"mime","message/rfc822",false},
        {"mj2","video/mj2",false},
        {"mjp2","video/mj2",false},
        {"mjs","application/javascript",false},
        {"mml","text/mathml",true},
        {"mods","application/mods+xml",true},
        {"mov","video/quicktime",false},
        {"mp2","audio/mpeg",false},
        {"mp21","application/mp21",false},
        {"mp2a","audio/mpeg",false},
        {"mp3","audio/mpeg",false},
        {"mp4","video/mp4",false},
        {"mp4a","audio/mp4",false},
        {"mp4s","application/mp4",false},
        {"mp4v","video/mp4",false},
        {"mpd","application/dash+xml",true},
        {"mpe","video/mpeg",false},
        {"mpeg","video/mpeg",false},
        {"mpg","video/mpeg",false},
        {"mpg4","video/mp4",false},
        {"mpga","audio/mpeg",false},
        {"mrc","application/marc",false},
        {"mrcx","application/marcxml+xml",true},
        {"ms","text/troff",true},
        {"mscml","application/mediaservercontrol+xml",true},
        {"msh","model/mesh",false},
        {"msi","application/octet-stream",false},
        {"msm","application/octet-stream",false},
        {"msp","application/octet-stream",false},
        {"mxf","application/mxf",false},
        {"mxml","application/xv+xml",true},
        {"n3","text/n3",true},
        {"nb","application/mathematica",false},
        {"oda","application/oda",false},
        {"oga","audio/ogg",false},
        {"ogg","audio/ogg",false},
        {"ogv","video/ogg",false},
        {"ogx","application/ogg",false},
        {"omdoc","application/omdoc+xml",true},
        {"onepkg","application/onenote",false},
        {"onetmp","application/onenote",false},
        {"onetoc","application/onenote",false},
        {"onetoc2","application/onenote",false},
        {"opf","application/oebps-package+xml",true},
        {"otf","font/otf",false},
        {"owl","application/rdf+xml",true},
        {"oxps","application/oxps",false},
        {"p10","application/pkcs10",false},
        {"p7c","application/pkcs7-mime",false},
        {"p7m","application/pkcs7-mime",false},
        {"p7s","application/pkcs7-signature",false},
        {"p8","application/pkcs8",false},
        {"pdf","application/pdf",false},
        {"pfr","application/font-tdpfr",false},
        {"pgp","application/pgp-encrypted",false},
        {"pkg","application/octet-stream",false},
        {"pki","application/pkixcmp",false},
        {"pkipath","application/pkix-pkipath",false},
        {"pls","application/pls+xml",true},
        {"png","image/png",false},
        {"prf","application/pics-rules",false},
        {"ps","application/postscript",false},
        {"pskcxml","application/pskc+xml",true},
        {"qt","video/quicktime",false},
        {"raml","application/raml+yaml",false},
        {"rdf","application/rdf+xml",true},
        {"rif","application/reginfo+xml",true},
        {"rl","application/resource-lists+xml",true},
        {"rld","application/resource-lists-diff+xml",true},
        {"rmi","audio/midi",false},
        {"rnc","application/relax-ng-compact-syntax",false},
        {"rng","application/xml",true},
        {"roa","application/rpki-roa",false},
        {"roff","text/troff",true},
        {"rq","application/sparql-query",false},
        {"rs","application/rls-services+xml",true},
        {"rsd","application/rsd+xml",true},
        {"rss","application/rss+xml",true},
        {"rtf","application/rtf",false},
        {"rtx","text/richtext",true},
        {"s3m","audio/s3m",false},
        {"sbml","application/sbml+xml",true},
        {"scq","application/scvp-cv-request",false},
        {"scs","application/scvp-cv-response",false},
        {"sdp","application/sdp",false},
        {"ser","application/java-serialized-object",false},
        {"setpay","application/set-payment-initiation",false},
        {"setreg","application/set-registration-initiation",false},
        {"sgi","image/sgi",false},
        {"sgm","text/sgml",true},
        {"sgml","text/sgml",true},
        {"shex","text/shex",true},
        {"shf","application/shf+xml",true},
        {"shtml","text/html",true},
        {"sig","application/pgp-signature",false},
        {"sil","audio/silk",false},
        {"silo","model/mesh",false},
        {"slim","text/slim",true},
        {"slm","text/slim",true},
        {"smi","application/smil+xml",true},
        {"smil","application/smil+xml",true},
        {"snd","audio/basic",false},
        {"so","application/octet-stream",false},
        {"spp","application/scvp-vp-response",false},
        {"spq","application/scvp-vp-request",false},
        {"spx","audio/ogg",false},
        {"sru","application/sru+xml",true},
        {"srx","application/sparql-results+xml",true},
        {"ssdl","application/ssdl+xml",true},
        {"ssml","application/ssml+xml",true},
        {"stk","application/hyperstudio",false},
        {"styl","text/stylus",true},
        {"stylus","text/stylus",true},
        {"svg","image/svg+xml",true},
        {"svgz","image/svg+xml",true},
        {"t","text/troff",true},
        {"t38","image/t38",false},
        {"tei","application/tei+xml",true},
        {"teicorpus","application/tei+xml",true},
        {"text","text/plain",true},
        {"tfi","application/thraud+xml",true},
        {"tfx","image/tiff-fx",false},
        {"tif","image/tiff",false},
        {"tiff","image/tiff",false},
        {"tr","text/troff",true},
        {"ts","video/mp2t",false},
        {"tsd","application/timestamped-data",false},
        {"tsv","text/tab-separated-values",true},
        {"ttc","font/collection",false},
        {"ttf","font/ttf",false},
        {"ttl","text/turtle",true},
        {"txt","text/plain",true},
        {"u8dsn","message/global-delivery-status",false},
        {"u8hdr","message/global-headers",false},
        {"u8mdn","message/global-disposition-notification",false},
        {"u8msg","message/global",false},
        {"uri","text/uri-list",true},
        {"uris","text/uri-list",true},
        {"urls","text/uri-list",true},
        {"vcard","text/vcard",true},
        {"vrml","model/vrml",false},
        {"vtt","text/vtt",true},
        {"vxml","application/voicexml+xml",true},
        {"war","application/java-archive",false},
        {"wasm","application/wasm",false},
        {"wav","audio/wav",false},
        {"weba","audio/webm",false},
        {"webm","video/webm",false},
        {"webmanifest","application/manifest+json",true},
        {"webp","image/webp",false},
        {"wgt","application/widget",false},
        {"wmf","image/wmf",false},
        {"woff","font/woff",false},
        {"woff2","font/woff2",false},
        {"wrl","model/vrml",false},
        {"wsdl","application/wsdl+xml",true},
        {"wspolicy","application/wspolicy+xml",true},
        {"x3d","model/x3d+xml",true},
        {"x3db","model/x3d+binary",false},
        {"x3dbz","model/x3d+binary",false},
        {"x3dv","model/x3d+vrml",false},
        {"x3dvz","model/x3d+vrml",false},
        {"x3dz","model/x3d+xml",true},
        {"xaml","application/xaml+xml",true},
        {"xdf","application/xcap-diff+xml",true},
        {"xdssc","application/dssc+xml",true},
        {"xenc","application/xenc+xml",true},
        {"xer","application/patch-ops-error+xml",true},
        {"xht","application/xhtml+xml",true},
        {"xhtml","application/xhtml+xml",true},
        {"xhvml","application/xv+xml",true},
        {"xm","audio/xm",false},
        {"xml","application/xml",true},
        {"xop","application/xop+xml",true},
        {"xpl","application/xproc+xml",true},
        {"xsd","application/xml",true},
        {"xsl","application/xml",true},
        {"xslt","application/xslt+xml",true},
        {"xspf","application/xspf+xml",true},
        {"xvm","application/xv+xml",true},
        {"xvml","application/xv+xml",true},
        {"yaml","text/yaml",true},
        {"yang","application/yang",false},
        {"yin","application/yin+xml",true},
        {"yml","text/yaml",true},
        {"zip","application/zip",false},
};
