find_path(GMOCK_INCLUDE_DIR gmock/gmock.h)

find_library(GMOCK_LIBRARIES gmock)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(gmock DEFAULT_MSG GMOCK_LIBRARIES GMOCK_INCLUDE_DIR)

mark_as_advanced(GMOCK_INCLUDE_DIR GMOCK_LIBRARIES)