find_path(GFLAGS_INCLUDE_DIR gflags/gflags.h)

find_library(GFLAGS_LIBRARIES gflags)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(gflags DEFAULT_MSG GFLAGS_LIBRARIES GFLAGS_INCLUDE_DIR)

mark_as_advanced(GFLAGS_INCLUDE_DIR GFLAGS_LIBRARIES)