name: Linux Compiler

on:
  push:
    branches: [ "main", "release/*" ]
  pull_request:
    branches: [ "main", "release/*" ]

jobs:
  gcc850:
    runs-on: [self-hosted, compiler]
    steps:
      - uses: actions/checkout@v3
      - name: Build850
        run: |
          rm -fr build
          cmake -B build -D CMAKE_BUILD_TYPE=MinSizeRel   \
                         -D PHOTON_BUILD_TESTING=ON       \
                         -D PHOTON_ENABLE_SASL=ON         \
                         -D PHOTON_ENABLE_FUSE=ON         \
                         -D PHOTON_ENABLE_URING=ON        \
                         -D PHOTON_ENABLE_EXTFS=ON        \
                         -D PHOTON_BUILD_DEPENDENCIES=ON  \
                         -D PHOTON_AIO_SOURCE=""          \
                         -D PHOTON_ZLIB_SOURCE=""         \
                         -D PHOTON_CURL_SOURCE=""         \
                         -D PHOTON_OPENSSL_SOURCE=""      \
                         -D PHOTON_GFLAGS_SOURCE=""       \
                         -D PHOTON_GOOGLETEST_SOURCE=""   \
                         -D PHOTON_URING_SOURCE=https://github.com/axboe/liburing/archive/refs/tags/liburing-2.3.tar.gz

          cmake --build build -j $(nproc) --clean-first -- VERBOSE=1
          cd build/output
          rm -f *.a
          for f in gtest gmock gflags libfuse libgsasl; do
            ln -s `ldd test-curl | grep $f | awk '{print $3}'` .
          done
          tar -c -h --use-compress-program=zstdmt -f ../../output850.tzs .
      - name: Upload850
        uses: actions/upload-artifact@v4
        with:
          name: output850
          path: output850.tzs
          retention-days: 5
          compression-level: 0

  test850:
    needs: gcc850
    runs-on: ubuntu-latest
    steps:
      - name: download850
        uses: actions/download-artifact@v4
        with:
          name: output850
      - name: test
        run: |
          tar -x --use-compress-program=zstdmt -f output850.tzs
          ls -R
          sudo apt-get update
          sudo apt-get install libgsasl
          ctest --timeout 3600 -V

  gcc921:
    needs: gcc850
    runs-on: [self-hosted, compiler]
    steps:
      - name: Build921
        run: |
          source /opt/rh/gcc-toolset-9/enable
          cmake --build build -j $(nproc) --clean-first -- VERBOSE=1
          rm -f build/output/*.a
          tar -c --use-compress-program=pigz -f output921.tgz build/output/
      - name: Upload921
        uses: actions/upload-artifact@v4
        with:
          name: output921.tgz
          path: output921.tgz
          retention-days: 5
          compression-level: 0

  gcc1031:
    needs: gcc921
    runs-on: [self-hosted, compiler]
    steps:
      - name: Build1031
        run: |
          source /opt/rh/gcc-toolset-10/enable
          cmake --build build -j $(nproc) --clean-first -- VERBOSE=1
          rm -f build/output/*.a
          tar -c --use-compress-program=pigz -f output1031.tgz build/output/
      - name: Upload1031
        uses: actions/upload-artifact@v4
        with:
          name: output1031.tgz
          path: output1031.tgz
          retention-days: 5
          compression-level: 0

  gcc1121:
    needs: gcc1031
    runs-on: [self-hosted, compiler]
    steps:
      - name: Build1121
        run: |
          source /opt/rh/gcc-toolset-10/enable
          cmake --build build -j --clean-first -- VERBOSE=1
          rm -f build/output/*.a
          tar -c --use-compress-program=pigz -f output1121.tgz build/output/
      - name: Upload1121
        uses: actions/upload-artifact@v4
        with:
          name: output1121.tgz
          path: output1121.tgz
          retention-days: 5
          compression-level: 0

  gcc1211:
    needs: gcc1121
    runs-on: [self-hosted, compiler]
    steps:
      - name: Build1211
        run: |
          source /opt/rh/gcc-toolset-10/enable
          cmake --build build -j $(nproc) --clean-first -- VERBOSE=1
          rm -f build/output/*.a
          tar -c --use-compress-program=pigz -f output1211.tgz build/output/
      - name: Upload1211
        uses: actions/upload-artifact@v4
        with:
          name: output1211.tgz
          path: output1211.tgz
          retention-days: 5
          compression-level: 0


