name: Linux Compiler

on:
  push:
    branches: [ "main", "release/*" ]
  pull_request:
    branches: [ "main", "release/*" ]

jobs:
  gcc850:
    runs-on: [self-hosted, compiler]

    steps:
      # - uses: szenius/set-timezone@v1.2
      #   with:
      #     timezoneLinux: "Asia/Shanghai"
      #     timezoneMacos: "Asia/Shanghai"
      #     timezoneWindows: "China Standard Time"

      - uses: actions/checkout@v3

      # - name: Install Dependencies
      #   run: |
      #     dnf install -y git gcc-c++ cmake 'dnf-command(config-manager)'
      #     dnf install -y gcc-toolset-9-gcc-c++
      #     dnf install -y openssl-devel libcurl-devel libaio-devel
      #     dnf install -y epel-release
      #     dnf config-manager --set-enabled powertools
      #     dnf install -y gtest-devel gmock-devel gflags-devel fuse-devel libgsasl-devel e2fsprogs-devel

      - name: Build850
        run: |
          cmake -B build -D CMAKE_BUILD_TYPE=MinSizeRel -D PHOTON_BUILD_TESTING=ON \
            -D PHOTON_ENABLE_SASL=ON -D PHOTON_ENABLE_FUSE=ON -D PHOTON_ENABLE_EXTFS=ON
          cmake --build build -j --clean-first -- VERBOSE=1
          rm -f build/output/*.a

      - name: Upload850
        uses: actions/upload-artifact@v4
        with:
          name: output850
          path: build/output

      - name: Build921
        run: |
          source /opt/rh/gcc-toolset-9/enable
          # cmake -B build -D CMAKE_BUILD_TYPE=MinSizeRel -D PHOTON_BUILD_TESTING=ON \
          #   -D PHOTON_ENABLE_SASL=ON -D PHOTON_ENABLE_FUSE=ON -D PHOTON_ENABLE_EXTFS=ON
          cmake --build build -j --clean-first -- VERBOSE=1
          rm -f build/output/*.a

      - name: Upload921
        uses: actions/upload-artifact@v4
        with:
          name: output921
          path: build/output

      - name: Build1031
        run: |
          source /opt/rh/gcc-toolset-10/enable
          # cmake -B build -D CMAKE_BUILD_TYPE=MinSizeRel -D PHOTON_BUILD_TESTING=ON \
          #   -D PHOTON_ENABLE_SASL=ON -D PHOTON_ENABLE_FUSE=ON -D PHOTON_ENABLE_EXTFS=ON
          cmake --build build -j --clean-first -- VERBOSE=1
          rm -f build/output/*.a

      - name: Upload1031
        uses: actions/upload-artifact@v4
        with:
          name: output1031
          path: build/output

      - name: Build1121
        run: |
          source /opt/rh/gcc-toolset-11/enable
          # cmake -B build -D CMAKE_BUILD_TYPE=MinSizeRel -D PHOTON_BUILD_TESTING=ON \
          #   -D PHOTON_ENABLE_SASL=ON -D PHOTON_ENABLE_FUSE=ON -D PHOTON_ENABLE_EXTFS=ON
          cmake --build build -j --clean-first -- VERBOSE=1
          rm -f build/output/*.a

      - name: Upload1121
        uses: actions/upload-artifact@v4
        with:
          name: output1121
          path: build/output

      - name: Build1211
        run: |
          source /opt/rh/gcc-toolset-12/enable
          # cmake -B build -D CMAKE_BUILD_TYPE=MinSizeRel -D PHOTON_BUILD_TESTING=ON \
          #   -D PHOTON_ENABLE_SASL=ON -D PHOTON_ENABLE_FUSE=ON -D PHOTON_ENABLE_EXTFS=ON
          cmake --build build -j --clean-first -- VERBOSE=1
          rm -f build/output/*.a

      - name: Upload1211
        uses: actions/upload-artifact@v4
        with:
          name: output1211
          path: build/output



