name: Linux Compiler

on:
  push:
    branches: [ "main", "release/*" ]
  pull_request:
    branches: [ "main", "release/*" ]

jobs:
  gcc850:
    runs-on: [self-hosted, compiler]
    steps:
      - uses: actions/checkout@v3
      - name: Build850
        run: |
          rm -fr build
          cmake -B build -D CMAKE_BUILD_TYPE=MinSizeRel -D PHOTON_BUILD_TESTING=ON \
            -D PHOTON_ENABLE_SASL=ON -D PHOTON_ENABLE_FUSE=ON -D PHOTON_ENABLE_EXTFS=ON
          cmake --build build -j $(nproc) --clean-first -- VERBOSE=1
          rm -f build/output/*.a
          mv build/output build/output850
          mkdir build/output

  upload850:
    needs: gcc850
    runs-on: [self-hosted, compiler]
    steps:
      - name: Upload850
        uses: actions/upload-artifact@v4
        with:
          name: output850
          path: build/output850
          retention-days: 5
          compression-level: 0

  gcc921:
    needs: gcc850
    runs-on: [self-hosted, compiler]
    steps:
      - name: Build921
        run: |
          source /opt/rh/gcc-toolset-9/enable
          cmake --build build -j $(nproc) --clean-first -- VERBOSE=1
          rm -f build/output/*.a
          mv build/output build/output921
          mkdir build/output

  upload921:
    needs: gcc921
    runs-on: [self-hosted, compiler]
    steps:
      - name: Upload921
        uses: actions/upload-artifact@v4
        with:
          name: output921
          path: build/output921
          retention-days: 5
          compression-level: 0

  gcc1031:
    needs: gcc921
    runs-on: [self-hosted, compiler]
    steps:
      - name: Build1031
        run: |
          source /opt/rh/gcc-toolset-10/enable
          cmake --build build -j $(nproc) --clean-first -- VERBOSE=1
          rm -f build/output/*.a
          mv build/output build/output1031
          mkdir build/output

  upload1031:
    needs: gcc1031
    runs-on: [self-hosted, compiler]
    steps:
      - name: Upload1031
        uses: actions/upload-artifact@v4
        with:
          name: output1031
          path: build/output1031
          retention-days: 5
          compression-level: 0

  gcc1121:
    needs: gcc1031
    runs-on: [self-hosted, compiler]
    steps:
      - name: Build1121
        run: |
          source /opt/rh/gcc-toolset-10/enable
          cmake --build build -j --clean-first -- VERBOSE=1
          rm -f build/output/*.a
          mv build/output build/output1121
          mkdir build/output

  upload1121:
    needs: gcc1121
    runs-on: [self-hosted, compiler]
    steps:
      - name: Upload1121
        uses: actions/upload-artifact@v4
        with:
          name: output1121
          path: build/output1121
          retention-days: 5
          compression-level: 0

  gcc1211:
    needs: gcc1121
    runs-on: [self-hosted, compiler]
    steps:
      - name: Build1211
        run: |
          source /opt/rh/gcc-toolset-10/enable
          cmake --build build -j $(nproc) --clean-first -- VERBOSE=1
          rm -f build/output/*.a
          mv build/output build/output1211
          mkdir build/output

  upload1211:
    needs: gcc1211
    runs-on: [self-hosted, compiler]
    steps:
      - name: Upload1211
        uses: actions/upload-artifact@v4
        with:
          name: output1211
          path: build/output1211
          retention-days: 5
          compression-level: 0


