name: Linux ARM

on:
  pull_request:
    types: [opened, synchronize, reopened, unlabeled]
    branches: [ "main", "release/*" ]

jobs:
  arm-linux-build-and-test:
    name: gcc${{ matrix.gcc }}-C++${{ matrix.cxx }}
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'needs-manual-merge') && (github.event.action != 'unlabeled' || github.event.label.name == 'needs-manual-merge') }}
    runs-on: ubuntu-24.04-arm
    container:
      image: ghcr.io/alibaba/photon-ut-base:latest
      options: --cpus 4 --shm-size 512m --privileged
    strategy:
      fail-fast: false
      matrix:
        include:
          - gcc: 9
            cxx: 14
          - gcc: 9
            cxx: 17
          - gcc: 11
            cxx: 20
          - gcc: 12
            cxx: 23
          - gcc: 13
            cxx: 23
          - gcc: 14
            cxx: 23
            run_test: true
    steps:
      - uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Shanghai"
          timezoneMacos: "Asia/Shanghai"
          timezoneWindows: "China Standard Time"

      - uses: actions/checkout@v4

      - name: Build
        run: |
          source /opt/rh/gcc-toolset-${{ matrix.gcc }}/enable
          cmake -B build -D CMAKE_BUILD_TYPE=MinSizeRel   \
                         -D PHOTON_CXX_STANDARD=${{ matrix.cxx }} \
                         -D PHOTON_ENABLE_ECOSYSTEM=ON    \
                         -D PHOTON_BUILD_TESTING=ON       \
                         -D PHOTON_ENABLE_SASL=ON         \
                         -D PHOTON_ENABLE_FUSE=ON         \
                         -D PHOTON_ENABLE_URING=ON        \
                         -D PHOTON_ENABLE_LIBCURL=ON      \
                         -D PHOTON_ENABLE_EXTFS=ON
          cmake --build build -j $(nproc) -- VERBOSE=1

      - name: Test
        if: matrix.run_test
        run: |
          cd build
          nohup redis-server &
          ctest -E test-lockfree --timeout 3600 -V
          pkill redis-server

  debug-build-from-source:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'needs-manual-merge') && (github.event.action != 'unlabeled' || github.event.label.name == 'needs-manual-merge') }}
    runs-on: ubuntu-24.04-arm
    container:
      image: almalinux:8
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          dnf install -y 'dnf-command(config-manager)'
          dnf config-manager --set-enabled powertools
          dnf -q -y install git gcc-c++ cmake gcc-toolset-9-gcc-c++ nasm
          source /opt/rh/gcc-toolset-9/enable
          cmake -B build -D CMAKE_BUILD_TYPE=Debug        \
                         -D PHOTON_BUILD_DEPENDENCIES=ON  \
                         -D PHOTON_BUILD_TESTING=ON       \
                         -D PHOTON_ENABLE_ECOSYSTEM=ON    \
                         -D PHOTON_ENABLE_SASL=OFF        \
                         -D PHOTON_ENABLE_FUSE=OFF        \
                         -D PHOTON_ENABLE_URING=ON        \
                         -D PHOTON_ENABLE_LIBCURL=OFF     \
                         -D PHOTON_ENABLE_EXTFS=OFF
          cmake --build build -j $(nproc)
