name: macOS ARM

on:
  push:
    branches: [ "main", "release/*" ]
  pull_request:
    types: [opened, synchronize, reopened, unlabeled]
    branches: [ "main", "release/*" ]

jobs:
<<<<<<< HEAD
  macOS-clang-debug:
    runs-on: macos-14
=======
  macOS14-arm:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'needs-manual-merge') && (github.event.action != 'unlabeled' || github.event.label.name == 'needs-manual-merge') }}
    runs-on: macos-15
>>>>>>> b4625a3 ([Backport][0.8 to 0.7] | | | ci: harden backport autopr with bugfix label gate, conflict handling, and CI skip (#1410) (#1471) (#1507) (#1520))

    steps:
      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Shanghai"
          timezoneMacos: "Asia/Shanghai"
          timezoneWindows: "China Standard Time"

      - uses: actions/checkout@v3

      - name: Install Dependencies
        shell: bash
        run: |
          brew install cmake openssl gflags googletest gsasl

      - name: Build
        run: |
          cmake -B ${{github.workspace}}/build -D PHOTON_BUILD_TESTING=ON -D CMAKE_BUILD_TYPE=Debug \
            -D PHOTON_ENABLE_SASL=ON -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl@3
          cmake --build ${{github.workspace}}/build -j -- VERBOSE=1

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest --timeout 3600 -V
